apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovetest-fruit-ns

metadata:
  name: lovetest-fruit
  namespace: lovetest-fruit-ns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/lovetest-fruit
  newTag: 1.0.6

commonLabels:
  app: lovetest-fruit
  managed-by: argocd


